# Generated by Django 4.2.3 on 2023-12-27 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='milage',
            new_name='mileage',
        ),
    ]
